name: redux_thunk
author: Brian Egan <brian@brianegan.com>
description: Redux Middleware for handling functions as actions
homepage: https://github.com/brianegan/redux_thunk
version: 0.2.0

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  redux: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ">=0.12.33 <0.13.0"
